[package]
name = "rc5librs"
version = "0.1.0"
edition = "2021"
authors = ["Andriy <yamukha@ukr.net>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
